# Valeurs possibles: «voyage» et «autre»
RaisonDépenses: autre

NoRef: -1

# Valeurs possibles: «employé(e)» et «étudiant(e)»
Étudiant(e) ou employé(e): étudiant(e)
Matricule: 666666
CodePermanent: DUPR01060901
Date: 2021-03-01

Prenom: Raphaëlle
Nom: Dupré
NomUA: club Cédille

Adresse: 1100, rue Notre-Dame Ouest
Ville: Montréal
CodePostal: H3C 1K3
Province: Québec
Courriel: raphaelle.dupre.1@ens.etsmtl.ca
# Valeurs possibles: «chèque» et «dépôt»
Chèque ou dépôt: chèque

# 60 caractères maximum
Description: Des choses
Destination: aucune destination
# Préiode de l'activité
DébutActivité: 2021-03-02
FinActivité: 2021-03-03
# Date de départ
Départ: 2021-03-04
# Date de retour
Retour: 2021-03-05

RaisonVoyage:
  Présentation:
    Cochée: true
    Sujet: plate
  Conférence:
    Cochée: true
    Nom: anonyme
  Sabbatique: false
  Autres:
    Cochée: true
    Précision: aliaj # «autres» en esperanto

# Limite de 8 dépenses
Dépenses:
  - Description: Dépense 1
    Montant: 1
  - Description: Dépense 2
    Montant: 2
  - Description: Dépense 3
    Montant: 3
  - Description: Dépense 4
    Montant: 4
  - Description: Dépense 5
    Montant: 5
  - Description: Dépense 6
    Montant: 6
  - Description: Dépense 7
    Montant: 7
  - Description: Dépense 8
    Montant: 8
Avance: 9
# Distance en kilomètres
Distance: 9002.321

# Limite de 5 codes comptables
Codes comptables:
  - UBR: 111111
    Compte: 11111
    DemFin: 11
    CBS: 111
    Montant: 11
  - UBR: 222222
    Compte: 22222
    DemFin: 22
    CBS: 222
    Montant: 22
  - UBR: 333333
    Compte: 33333
    DemFin: 33
    CBS: 333
    Montant: 33
  - UBR: 444444
    Compte: 44444
    DemFin: 44
    CBS: 444
    Montant: 44
  - UBR: 555555
    Compte: 55555
    DemFin: 55
    CBS: 555
    Montant: 55

Verifié C/P:
Date vérifié C/P:
autorisation budgétaire:
Date autorisation budgétaire:

# Signatures et numéros de téléphone
SignatureDemandeur:
TelDemandeur: 514 666-0001
SignatureRequérant:
NomRequérant: Cunégonde Gonzalez
SignatureSupHiérarchique:
NomSupHiérarchique: Alexandre Robitaille
